name: Taskwarrior Web
version: "1.0.0"
slug: taskwarrior_web

description: Web interface for Taskwarrior

arch:
  - amd64
  - aarch64

startup: services
boot: auto

init: false

ingress: true
ingress_port: 80
panel_icon: mdi:clipboard-check

map:
  - config:rw

options: {}

schema: {}